services:
  depsrag-app:
    build: .
    ports:
      - "4000:80" # For CLI mode
      - "8501:8501" # For Chainlit UI mode
    volumes:
      - ./html:/app/html # Map the host's html directory to the container's /app/html directory
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      NEO4J_DATABASE: neo4j
      HOST_HTML_PATH: ${PWD}/html

  neo4j:
    image: neo4j:5.11
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
      NEO4J_dbms_security_procedures_allowlist: "apoc.load.*,apoc.*"
      NEO4J_dbms_logs_debug_level: "DEBUG"
      NEO4J_dbms_memory_pagecache_size: 2G
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
      NEO4J_PLUGINS: '["apoc"]'
